---
title: "Comorbidity Analysis"
author: "Josue Rodriguez"
date: "3/27/2020"
output: 
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
  html_notebook: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)
```

# Set up

```{r setup2, message=FALSE}
# libraries
library(BGGM)
library(MASS)
library(networktools)
library(network)
library(ggplot2)
source("03-plot-adj.R")


set.seed(27)

net_data <- read.csv("data/01-cov-anxdep.csv")[, -1]
print(names(net_data))

sim_data <- MASS::mvrnorm(n = 1029, mu = rep(0, 16), Sigma = net_data, empirical = TRUE)

col_names <- 
  sub(pattern = "[A-Z].",
      replacement = "",
      x = colnames(net_data)) 

col_names <- tolower(col_names)

colnames(sim_data) <- col_names
node_names <- 
  c(
    paste0("D", 1:9),
    paste0("A", 1:7)
  )

comms <- c(
  rep("depression", 9),
  rep("anxiety", 7)
)


pal <-  ggthemes::colorblind_pal()(8)[c(4, 6)]

split <- sample(1:1029, size = floor(1029 * .5))

exp1 <- explore(sim_data[split, ], prior_sd = 0.25)
slct1 <- BGGM::select(exp1, alternative = "greater", BF_cut = 3)
```



# Exploratory analysis
## Visual

```{r explore-visual}
# pcor_matrix
pcors_exp <- round(slct1$pcor_mat_zero, 2)
dimnames(pcors_exp) <- list(node_names, node_names)


# make_adj_plot(slct1$Adj_20,
#               communities = comms,
#               node_labels = node_names) +
#   ggthemes::scale_fill_few() +A
#   theme_blank() +
#   theme(legend.position = "top")
```

## Bridge Strength

```{r bridge, warning=FALSE}
bridge_strengths <- sort(bridge(pcors_exp, communities = comms)$`Bridge Strength`, decreasing = TRUE) 
bridge_strength_cutoff <- quantile(bridge_strengths, 0.9)
bridge_strengths[bridge_strengths > bridge_strength_cutoff]
```

## Correlation Table
```{r pcor_table, echo=FALSE, message=FALSE, warning=FALSE}
library(dplyr)
select <- BGGM::select
library(knitr)
library(kableExtra)
pnonzero <- pcors_exp %>% as.data.frame
# pnonzero[1:9, 1:9] <- 0
# pnonzero[10:16, 10:16] <- 0

pnonzero %>%
  mutate(` ` = node_names) %>%
  dplyr::select(` `, everything()) %>%
  mutate_if(is.numeric, function(x){
    cell_spec(x,
              bold = T,
              font_size = ifelse(x > 0, 14, 0))
  }) %>%
  kable(escape = FALSE, align = "c") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"))
```



## Plots
```{r adj_plots, include=FALSE, fig.height=6, fig.width=8}
plot_cd <-
  make_adj_plot(slct1$Adj_20,
                node_labels = node_names,
                node_label_col = "white",
                communities = comms,
                bridges = c("D8", "D6"),
                fade = c(
                  paste0("D", c(1:5, 7, 9)),
                  paste0("A", c(1, 2, 4))
                ),
              node_size = 12,
              type = "cd")  +
  scale_fill_manual(values = pal,
                    labels = c("Anxiety", "Depression")) +
  theme_facet() +
  theme(legend.position = "top",
        legend.text = element_text(size = 14),
        legend.title = element_blank())

plot_ci <-
  make_adj_plot(slct1$Adj_02,
              node_labels = node_names,
              node_label_col = "white",
              communities = comms,
              bridges = paste0("D", 1),
              fade = NULL,
              type = "ci",
              node_size = 12) +
  scale_fill_manual(values = pal,
                    labels = c("Anxiety", "Depression")) +
  theme_facet() +
  theme(legend.position = "top",
        legend.box.background = element_blank(),
        legend.background = element_blank(),
        legend.title = element_blank())

print(plot_cd)
print(plot_ci)
```




```{r plot-bridges}
coords <- 
  data.frame(
    x = c(1, 1, 2, 2, 3, 3),
    y = c(1, 4, 2, 3, 1, 4),
    comm = c("A", "A", "D", "D", "A", "A"),
    node = c("A5", "A3", "D8", "D6", "A7", "A6")
    )
    

plot_bridges <-
  ggplot(coords, aes(x, y)) +
  # bridge cors (d8 first)
  annotate(geom = "segment",
           x = rep(2, 4),
           xend = c(1, 3, 1, 3),
           y = c(2, 2, 3, 3),
           yend = c(1, 1, 4, 4),
           linetype = c(2, 2, 1, 1),
           size = 1) +
  # # independent
  annotate(geom = "segment",
           x =    c(2, 2, 2, 2, 2),
           xend = c(2, 1, 3, 1, 3),
           y =    c(2, 2, 2, 3, 3),
           yend = c(3, 4, 4, 1, 1),
           linetype = "dotted",
           col = "gray70") +
  # A nodes
  annotate(geom = "segment",
           x = c(1, 1, 3),
           xend = c(1, 3, 3),
           y = c(1, 4, 4),
           yend = c(4, 4, 1),
           linetype = c(3, 3, 1),
           col = "gray70") +
  # # bridge cor labels
  annotate(geom = "label",
           label = c("0.17", "0.10", "0.21", "0.20"),
           x =     c(1.5, 2.5, 1.5, 2.5),
           y =     c(3.5, 3.5, 1.5, 1.5)) +
  geom_point(size = 21) +
  geom_point(aes(fill = comm), 
             size = 20, 
             shape = 21,
             show.legend = FALSE) +
  geom_text(aes(label = node), col = "white") +
  lims(x = c(0.9, 3.1), y = c(0.8, 4.2))  +
  scale_fill_manual(values = pal) +
  theme_facet()
```


```{r make_legend, include=FALSE}
tst <- data.frame(x = 1:4,
                  y = 1:4,
                  g = c("A", "B", "C", "D"))
labs <- c(expression("Bridge: "*italic(D)*"6"),
          expression("Bridge: "*italic(D)*"8"),
          "Cond. Dep.",
          "Cond. Ind."
          # expression(italic(CD)),
          # expression(italic(CI))
          )

plot_legend_line <-
  ggplot(tst, aes(x, y)) +
  geom_line(aes(linetype = g, col = g)) +
  scale_linetype_manual(labels = labs,
                        values = c(1, 2, 1, 3)) +
  scale_color_manual(labels = labs,
                     values = c("black", "black", "gray70", "gray70")) +
  guides(linetype = guide_legend(override.aes = list(size = 1))) +
  theme_blank()+
  theme(legend.position = "top",
        legend.title = element_blank(),
        legend.text = element_text(size = 14),
        legend.key.width = unit(1, "cm"),
        legend.box.background = element_blank()) 
  
```

### Final Plot

```{r plot_all, message=FALSE, fig.height=8, fig.width=8}
library(cowplot)
# plot networks
plt_grid1 <- 
  plot_grid(plot_cd + theme(legend.position = "none"),
            plot_ci + theme(legend.position = "none"),
            ncol = 2)

# plot zoomed in 
plt_grid2 <- 
  plot_grid(NULL,
            plot_bridges,
            NULL,
            ncol = 3,
            rel_widths = c(1, 15, 1))
plt_grid_legend <- 
  plot_grid(
            NULL,
            get_legend(plot_cd), 
            get_legend(plot_legend_line), 
            NULL,
            rel_widths = c(0.1, 20, 20, 1),
            ncol = 4
            )


plt_grid <- plot_grid(plt_grid1,
                      plt_grid2,
                      nrow = 2,
                      rel_heights = c(5.5,4.5))
all_plots <-
  plot_grid(plt_grid_legend,
            plt_grid,
            nrow = 2,
            rel_heights = c(1, 10)) +
  draw_label("A",
             x = 0.04 ,
             y = 0.875,
             size = 40) +
  draw_label("B",
             x = 0.54 ,
             y = 0.875,
             size = 40) +
  draw_label("C",
             x = 0.05 ,
             y = 0.385,
             size = 40)

print(all_plots)
```

```{r save-ptsd-plot, include=FALSE, eval=FALSE}
ggsave("figs/02-plot-anxdep-2.pdf",
       plot = all_plots,
       dpi = 320,
       height = 4 * 3,
       width = 4 * 3)
```



# Confirmatory

```{r, generate-confirm-data}
confirm_data <- sim_data[-split, ]
colnames(confirm_data) <-  node_names
```

```{r confirm-network}
# explore and select graph
expl2 <- explore(confirm_data)
slct2 <- BGGM::select(expl2, alternative = "greater", bf_cut = 3)
pcors_conf <- round(slct2$pcor_mat_zero, 2)
dimnames(pcors_conf) <- list(node_names, node_names)
```

```{r}
bridge_strengths <- sort(bridge(pcors_conf, communities = comms)$`Bridge Strength`, decreasing = TRUE) 
bridge_strength_cutoff <- quantile(bridge_strengths, 0.9)
bridge_strengths[bridge_strengths > bridge_strength_cutoff]
```

```{r}
# plot bridge edges
make_adj_plot(slct2$Adj_20,
              node_labels = node_names,
              node_label_col = "white",
              communities = comms,
              bridges = c("D8", "A5"),
              fade = c(
                paste0("D", c(1:5, 7, 9)),
                paste0("A", c(2, 4, 6))
                ),
              node_size = 12,
              type = "cd")  +
  scale_fill_manual(values = pal,
                    labels = c("Anxiety", "Depression")) +
  theme_facet() +
  theme(legend.position = "top",
        legend.text = element_text(size = 14),
        legend.title = element_blank())
```


## Hypothesis D8
```{r include=F, eval=F}

hyp_d8 <- c("(D8--A5, D8--A7) > (D6--A3, D6--A6) > 0;
             D8--A5 > D8--A7 > D6--A3 > D6--A6 > 0")

confirm_d8 <- confirm(Y = confirm_data,
                      hypothesis = hyp_d8,
                      iter = 50000)
confirm_d8
```

## Hypothesis D8
```{r, hyp-d8}
hyp_d8 <- c("D8--A5 = D8--A7 > (D6--A3, D6--A6) > 0;
             D8--A5 > D8--A7 > D6--A3 > D6--A6 > 0")

confirm_d8 <- confirm(Y = confirm_data,
                      hypothesis = hyp_d8,
                      iter = 50000)
confirm_d8
```

## Hypothesis Null

```{r, hyp-null}
hyp_null <- c("(D8--A3, D8--A6) = 0;
               (D8--A3, D8--A6) > 0")
confirm_null <- confirm(confirm_data,
                        hypothesis = hyp_null,
                        iter = 50000)
confirm_null
```

## Hypothesis Null 2
```{r, hyp-null2}
hyp_null2 <- c("(D6--A5, D8--A7) = 0;
                (D6--A5, D8--A7) > 0")

confirm_null2 <- confirm(confirm_data,
                         hypothesis = hyp_null2,
                         iter = 50000)
confirm_null2
```

## Hypothesis Null 3

```{r hyp-null3}
hyp_null3 <- c("D6--D8 = 0;
                D6--D8 > 0;
                D6--D8 < 0")

confirm_null3 <- confirm(confirm_data,
                         hypothesis = hyp_null3,
                         iter = 50000)
confirm_null3
```



